# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/x3/setup-makefiles.sh

# ACDB - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/lenovo/x3/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/lenovo/x3/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/lenovo/x3/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/lenovo/x3/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/lenovo/x3/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/lenovo/x3/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb

# ADSP - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/lenovo/x3/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so

# Audio - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/etc/firmware/tfa98xx.cnt:system/etc/firmware/tfa98xx.cnt \
    vendor/lenovo/x3/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so \
    vendor/lenovo/x3/proprietary/vendor/lib/hw/sound_trigger.primary.msm8994.so:system/vendor/lib/hw/sound_trigger.primary.msm8994.so \
    vendor/lenovo/x3/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/lenovo/x3/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/lenovo/x3/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libhwdaphal.so:system/vendor/lib64/libhwdaphal.so

# Bluetooth - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/btnvtool:system/vendor/bin/btnvtool \
    vendor/lenovo/x3/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/lenovo/x3/proprietary/vendor/bin/wcnss_filter:system/vendor/bin/wcnss_filter \
    vendor/lenovo/x3/proprietary/vendor/firmware/nvm_tlv.bin:system/vendor/firmware/nvm_tlv.bin \
    vendor/lenovo/x3/proprietary/vendor/firmware/nvm_tlv_1.3.bin:system/vendor/firmware/nvm_tlv_1.3.bin \
    vendor/lenovo/x3/proprietary/vendor/firmware/nvm_tlv_2.1.bin:system/vendor/firmware/nvm_tlv_2.1.bin \
    vendor/lenovo/x3/proprietary/vendor/firmware/nvm_tlv_3.0.bin:system/vendor/firmware/nvm_tlv_3.0.bin \
    vendor/lenovo/x3/proprietary/vendor/firmware/nvm_tlv_3.2.bin:system/vendor/firmware/nvm_tlv_3.2.bin \
    vendor/lenovo/x3/proprietary/vendor/firmware/rampatch_tlv.img:system/vendor/firmware/rampatch_tlv.img \
    vendor/lenovo/x3/proprietary/vendor/firmware/rampatch_tlv_1.3.tlv:system/vendor/firmware/rampatch_tlv_1.3.tlv \
    vendor/lenovo/x3/proprietary/vendor/firmware/rampatch_tlv_2.1.tlv:system/vendor/firmware/rampatch_tlv_2.1.tlv \
    vendor/lenovo/x3/proprietary/vendor/firmware/rampatch_tlv_3.0.tlv:system/vendor/firmware/rampatch_tlv_3.0.tlv \
    vendor/lenovo/x3/proprietary/vendor/firmware/rampatch_tlv_3.2.tlv:system/vendor/firmware/rampatch_tlv_3.2.tlv \
    vendor/lenovo/x3/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so

# Camera - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/lenovo/x3/proprietary/lib/libFNVfbEngineLib.so:system/lib/libFNVfbEngineLib.so \
    vendor/lenovo/x3/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/lenovo/x3/proprietary/lib/libmorpho_video_refiner.so:system/lib/libmorpho_video_refiner.so \
    vendor/lenovo/x3/proprietary/lib/libopcamerahw_interface.so:system/lib/libopcamerahw_interface.so \
    vendor/lenovo/x3/proprietary/lib64/libopcamera.so:system/lib64/libopcamera.so \
    vendor/lenovo/x3/proprietary/lib64/libopcameralib.so:system/lib64/libopcameralib.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libjpegdmahw.so:system/vendor/lib/libjpegdmahw.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_sensor_debug.so:system/vendor/lib/libmmcamera2_sensor_debug.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_cac2_lib.so:system/vendor/lib/libmmcamera_cac2_lib.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    vendor/lenovo/x3/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libois_rohm_bu63165gwl.so:system/vendor/lib/libois_rohm_bu63165gwl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:system/vendor/lib/libqomx_jpegenc_pipe.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmmcamera2_q3a_core.so:system/vendor/lib64/libmmcamera2_q3a_core.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmmcamera2_sensor_debug.so:system/vendor/lib64/libmmcamera2_sensor_debug.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmmcamera2_stats_algorithm.so:system/vendor/lib64/libmmcamera2_stats_algorithm.so

# Camera actuators - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib/libactuator_rohm_bu63165gwl.so:system/vendor/lib/libactuator_rohm_bu63165gwl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libactuator_rohm_bu63165gwl_camcorder.so:system/vendor/lib/libactuator_rohm_bu63165gwl_camcorder.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libactuator_rohm_bu63165gwl_camera.so:system/vendor/lib/libactuator_rohm_bu63165gwl_camera.so

# Camera chromatix - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_common.so:system/vendor/lib/libchromatix_ov13860_common.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_cpp_hfr.so:system/vendor/lib/libchromatix_ov13860_cpp_hfr.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_cpp_liveshot.so:system/vendor/lib/libchromatix_ov13860_cpp_liveshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_cpp_panorama.so:system/vendor/lib/libchromatix_ov13860_cpp_panorama.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_cpp_preview.so:system/vendor/lib/libchromatix_ov13860_cpp_preview.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_cpp_snapshot.so:system/vendor/lib/libchromatix_ov13860_cpp_snapshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_cpp_video.so:system/vendor/lib/libchromatix_ov13860_cpp_video.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_cpp_zsl.so:system/vendor/lib/libchromatix_ov13860_cpp_zsl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_default_video.so:system/vendor/lib/libchromatix_ov13860_default_video.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_hfr.so:system/vendor/lib/libchromatix_ov13860_hfr.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_liveshot.so:system/vendor/lib/libchromatix_ov13860_liveshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_panorama.so:system/vendor/lib/libchromatix_ov13860_panorama.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_postproc.so:system/vendor/lib/libchromatix_ov13860_postproc.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_preview.so:system/vendor/lib/libchromatix_ov13860_preview.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_quarter_size_video.so:system/vendor/lib/libchromatix_ov13860_quarter_size_video.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_snapshot.so:system/vendor/lib/libchromatix_ov13860_snapshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov13860_zsl.so:system/vendor/lib/libchromatix_ov13860_zsl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_cpp_liveshot.so:system/vendor/lib/libchromatix_ov5648_15fps_cpp_liveshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_cpp_preview.so:system/vendor/lib/libchromatix_ov5648_15fps_cpp_preview.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_cpp_snapshot.so:system/vendor/lib/libchromatix_ov5648_15fps_cpp_snapshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_cpp_video.so:system/vendor/lib/libchromatix_ov5648_15fps_cpp_video.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_postproc.so:system/vendor/lib/libchromatix_ov5648_15fps_postproc.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_preview.so:system/vendor/lib/libchromatix_ov5648_15fps_preview.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_snapshot.so:system/vendor/lib/libchromatix_ov5648_15fps_snapshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_15fps_video.so:system/vendor/lib/libchromatix_ov5648_15fps_video.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_cpp_liveshot.so:system/vendor/lib/libchromatix_ov5648_30fps_cpp_liveshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_cpp_preview.so:system/vendor/lib/libchromatix_ov5648_30fps_cpp_preview.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_cpp_snapshot.so:system/vendor/lib/libchromatix_ov5648_30fps_cpp_snapshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_cpp_video.so:system/vendor/lib/libchromatix_ov5648_30fps_cpp_video.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_postproc.so:system/vendor/lib/libchromatix_ov5648_30fps_postproc.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_preview.so:system/vendor/lib/libchromatix_ov5648_30fps_preview.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_snapshot.so:system/vendor/lib/libchromatix_ov5648_30fps_snapshot.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_30fps_video.so:system/vendor/lib/libchromatix_ov5648_30fps_video.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libchromatix_ov5648_common.so:system/vendor/lib/libchromatix_ov5648_common.so

# Camera firmware - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lenovo/x3/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lenovo/x3/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lenovo/x3/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lenovo/x3/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/lenovo/x3/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw

# Camera sensors - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_abf44.so:system/vendor/lib/libmmcamera_isp_abf44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_bcc44.so:system/vendor/lib/libmmcamera_isp_bcc44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_bf_scale_stats46.so:system/vendor/lib/libmmcamera_isp_bf_scale_stats46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_bf_stats44.so:system/vendor/lib/libmmcamera_isp_bf_stats44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_bg_stats46.so:system/vendor/lib/libmmcamera_isp_bg_stats46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_bpc44.so:system/vendor/lib/libmmcamera_isp_bpc44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_clf46.so:system/vendor/lib/libmmcamera_isp_clf46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_color_correct46.so:system/vendor/lib/libmmcamera_isp_color_correct46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder46.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_color_xform_video46.so:system/vendor/lib/libmmcamera_isp_color_xform_video46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_cs_stats46.so:system/vendor/lib/libmmcamera_isp_cs_stats46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_demosaic44.so:system/vendor/lib/libmmcamera_isp_demosaic44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_fovcrop_video46.so:system/vendor/lib/libmmcamera_isp_fovcrop_video46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_gamma44.so:system/vendor/lib/libmmcamera_isp_gamma44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_gic46.so:system/vendor/lib/libmmcamera_isp_gic46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_gtm46.so:system/vendor/lib/libmmcamera_isp_gtm46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_hdr46.so:system/vendor/lib/libmmcamera_isp_hdr46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_hdr_be_stats46.so:system/vendor/lib/libmmcamera_isp_hdr_be_stats46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_ihist_stats46.so:system/vendor/lib/libmmcamera_isp_ihist_stats46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff44.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_pedestal_correct46.so:system/vendor/lib/libmmcamera_isp_pedestal_correct46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_rs_stats46.so:system/vendor/lib/libmmcamera_isp_rs_stats46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder46.so:system/vendor/lib/libmmcamera_isp_scaler_encoder46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_scaler_video46.so:system/vendor/lib/libmmcamera_isp_scaler_video46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_isp_wb46.so:system/vendor/lib/libmmcamera_isp_wb46.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_ov13860.so:system/vendor/lib/libmmcamera_ov13860.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_ov13860_eeprom.so:system/vendor/lib/libmmcamera_ov13860_eeprom.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_ov5648.so:system/vendor/lib/libmmcamera_ov5648.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmcamera_ov5648_eeprom.so:system/vendor/lib/libmmcamera_ov5648_eeprom.so

# DRM - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/lenovo/x3/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so

# Fingerprint sensor - VIBEUI_V3.1_1626_5.611.1_ST
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/lib/hw/fingerprint.msm8992.so:system/lib/hw/fingerprint.msm8992.so \
    vendor/lenovo/x3/proprietary/lib/lib_fpc_tac_shared.so:system/lib/lib_fpc_tac_shared.so \
    vendor/lenovo/x3/proprietary/lib64/hw/fingerprint.msm8992.so:system/lib64/hw/fingerprint.msm8992.so \
    vendor/lenovo/x3/proprietary/lib64/lib_fpc_tac_shared.so:system/lib64/lib_fpc_tac_shared.so

# Gatekeeper - VIBEUI_V3.1_1626_5.611.1_ST
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib/hw/gatekeeper.msm8992.so:system/vendor/lib/hw/gatekeeper.msm8992.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/hw/gatekeeper.msm8992.so:system/vendor/lib64/hw/gatekeeper.msm8992.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/loc_launcher:system/vendor/bin/loc_launcher \
    vendor/lenovo/x3/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/lenovo/x3/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/lenovo/x3/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/lenovo/x3/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libalarmservice_jni.so:system/vendor/lib64/libalarmservice_jni.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libdataitems.so:system/vendor/lib64/libdataitems.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/liblocationservice.so:system/vendor/lib64/liblocationservice.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/liblocationservice_glue.so:system/vendor/lib64/liblocationservice_glue.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/liblowi_client.so:system/vendor/lib64/liblowi_client.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/liblowi_wifihal.so:system/vendor/lib64/liblowi_wifihal.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libquipc_os_api.so:system/vendor/lib64/libquipc_os_api.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libulp2.so:system/vendor/lib64/libulp2.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libxtadapter.so:system/vendor/lib64/libxtadapter.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:system/vendor/lib64/libxtwifi_ulp_adaptor.so

# Graphics - kanged from Angler OPM3.171019.019
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/lenovo/x3/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    vendor/lenovo/x3/proprietary/vendor/lib/hw/vulkan.msm8994.so:system/vendor/lib/hw/vulkan.msm8994.so \
    vendor/lenovo/x3/proprietary/vendor/lib/hw/vulkan.msm8992.so:system/vendor/lib/hw/vulkan.msm8992.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libllvm-qgl.so:system/vendor/lib/libllvm-qgl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    vendor/lenovo/x3/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/egl/libq3dtools_esx.so:system/vendor/lib64/egl/libq3dtools_esx.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/hw/vulkan.msm8994.so:system/vendor/lib64/hw/vulkan.msm8994.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/hw/vulkan.msm8992.so:system/vendor/lib64/hw/vulkan.msm8992.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libllvm-qgl.so:system/vendor/lib64/libllvm-qgl.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \

# Graphics firmware - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/lenovo/x3/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw

# Keystore - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib64/hw/keystore.msm8994.so:system/vendor/lib64/hw/keystore.msm8994.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libcrypto_keystore.so:system/vendor/lib64/libcrypto_keystore.so

# Media - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libDivxDrm.so:system/vendor/lib64/libDivxDrm.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libI420colorconvert.so:system/vendor/lib64/libI420colorconvert.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libOmxAacDec.so:system/vendor/lib64/libOmxAacDec.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libOmxAmrwbplusDec.so:system/vendor/lib64/libOmxAmrwbplusDec.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libOmxWmaDec.so:system/vendor/lib64/libOmxWmaDec.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libSHIMDivxDrm.so:system/vendor/lib64/libSHIMDivxDrm.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmm-color-convertor.so:system/vendor/lib64/libmm-color-convertor.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmmosal.so:system/vendor/lib64/libmmosal.so

# Media firmware - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/lenovo/x3/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/lenovo/x3/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/lenovo/x3/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/lenovo/x3/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/lenovo/x3/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/lenovo/x3/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

# Perf - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/energy-awareness:system/vendor/bin/energy-awareness \
    vendor/lenovo/x3/proprietary/vendor/bin/msm_irqbalance:system/vendor/bin/msm_irqbalance \
    vendor/lenovo/x3/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/lenovo/x3/proprietary/vendor/etc/perf-profile0.conf:system/vendor/etc/perf-profile0.conf \
    vendor/lenovo/x3/proprietary/vendor/etc/perf-profile1.conf:system/vendor/etc/perf-profile1.conf \
    vendor/lenovo/x3/proprietary/vendor/etc/perf-profile2.conf:system/vendor/etc/perf-profile2.conf \
    vendor/lenovo/x3/proprietary/vendor/etc/perf-profile3.conf:system/vendor/etc/perf-profile3.conf \
    vendor/lenovo/x3/proprietary/vendor/etc/perf-profile4.conf:system/vendor/etc/perf-profile4.conf \
    vendor/lenovo/x3/proprietary/vendor/etc/perf-profile5.conf:system/vendor/etc/perf-profile5.conf \
    vendor/lenovo/x3/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so

# Peripheral manager - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/pm-proxy:system/vendor/bin/pm-proxy \
    vendor/lenovo/x3/proprietary/vendor/bin/pm-service:system/vendor/bin/pm-service \
    vendor/lenovo/x3/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so

# Postprocessing - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/mm-pp-daemon:system/vendor/bin/mm-pp-daemon \
    vendor/lenovo/x3/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmm-als.so:system/vendor/lib64/libmm-als.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so

# QMI - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/lenovo/x3/proprietary/vendor/etc/permissions/qti_libpermissions.xml:system/vendor/etc/permissions/qti_libpermissions.xml \
    vendor/lenovo/x3/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/lenovo/x3/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so

# Radio - VIBEUI_V3.1_1626_5.611.1_ST + OxygenOS 5.0 and OB30/OB21
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/lenovo/x3/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/lenovo/x3/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/lenovo/x3/proprietary/vendor/bin/rfs_access:system/vendor/bin/rfs_access \
    vendor/lenovo/x3/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/lenovo/x3/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/lenovo/x3/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/lenovo/x3/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
    vendor/lenovo/x3/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/lenovo/x3/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/lenovo/x3/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/lenovo/x3/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/lenovo/x3/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/lenovo/x3/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/lenovo/x3/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    vendor/lenovo/x3/proprietary/vendor/lib64/com.quicinc.cne.api@1.0.so:system/vendor/lib64/com.quicinc.cne.api@1.0.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/com.quicinc.cne.constants@1.0.so:system/vendor/lib64/com.quicinc.cne.constants@1.0.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/lenovo/x3/proprietary/vendor/qcril.db:system/vendor/qcril.db

# Radio - IMS - MIUI Hydrogen 7.7.6 global dev
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/ims_rtp_daemon:system/vendor/bin/ims_rtp_daemon \
    vendor/lenovo/x3/proprietary/vendor/bin/imscmservice:system/vendor/bin/imscmservice \
    vendor/lenovo/x3/proprietary/vendor/bin/imsdatadaemon:system/vendor/bin/imsdatadaemon \
    vendor/lenovo/x3/proprietary/vendor/bin/imsqmidaemon:system/vendor/bin/imsqmidaemon \
    vendor/lenovo/x3/proprietary/etc/permissions/imscm.xml:system/etc/permissions/imscm.xml \
    vendor/lenovo/x3/proprietary/framework/imscmlibrary.jar:system/framework/imscmlibrary.jar \
    vendor/lenovo/x3/proprietary/framework/rcsimssettings.jar:system/framework/rcsimssettings.jar \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-dplmedia.so:system/vendor/lib64/lib-dplmedia.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-ims-rcscmjni.so:system/vendor/lib64/lib-ims-rcscmjni.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsSDP.so:system/vendor/lib64/lib-imsSDP.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imscamera.so:system/vendor/lib64/lib-imscamera.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsdpl.so:system/vendor/lib64/lib-imsdpl.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsqimf.so:system/vendor/lib64/lib-imsqimf.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsrcs.so:system/vendor/lib64/lib-imsrcs.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsrcscm.so:system/vendor/lib64/lib-imsrcscm.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsrcscmclient.so:system/vendor/lib64/lib-imsrcscmclient.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsrcscmservice.so:system/vendor/lib64/lib-imsrcscmservice.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imss.so:system/vendor/lib64/lib-imss.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsvt.so:system/vendor/lib64/lib-imsvt.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-imsxml.so:system/vendor/lib64/lib-imsxml.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-rcsimssjni.so:system/vendor/lib64/lib-rcsimssjni.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-rtpcommon.so:system/vendor/lib64/lib-rtpcommon.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-rtpcore.so:system/vendor/lib64/lib-rtpcore.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-rtpdaemoninterface.so:system/vendor/lib64/lib-rtpdaemoninterface.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/lib-rtpsl.so:system/vendor/lib64/lib-rtpsl.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libimscamera_jni.so:system/vendor/lib64/libimscamera_jni.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libimsmedia_jni.so:system/vendor/lib64/libimsmedia_jni.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/librcc.so:system/vendor/lib64/librcc.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libvoice-svc.so:system/vendor/lib64/libvoice-svc.so

# Sensors - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/sensors.qcom:system/vendor/bin/sensors.qcom \
    vendor/lenovo/x3/proprietary/vendor/etc/sensors/hals.conf:system/vendor/etc/sensors/hals.conf \
    vendor/lenovo/x3/proprietary/etc/sensors/sensor_def_qcomdev.conf:system/etc/sensors/sensor_def_qcomdev.conf \
    vendor/lenovo/x3/proprietary/vendor/lib/hw/activity_recognition.msm8994.so:system/vendor/lib/hw/activity_recognition.msm8994.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libsensor_thresh.so:system/vendor/lib/libsensor_thresh.so \
    vendor/lenovo/x3/proprietary/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
    vendor/lenovo/x3/proprietary/vendor/lib/sensors.ssc.so:system/vendor/lib/sensors.ssc.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/hw/activity_recognition.msm8994.so:system/vendor/lib64/hw/activity_recognition.msm8994.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libsensor1.so:system/vendor/lib64/libsensor1.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libsensor_reg.so:system/vendor/lib64/libsensor_reg.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libsensor_thresh.so:system/vendor/lib64/libsensor_thresh.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libsensor_user_cal.so:system/vendor/lib64/libsensor_user_cal.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/sensors.ssc.so:system/vendor/lib64/sensors.ssc.so

# Thermal - OxygenOS 3.6.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/etc/thermal-engine.conf:system/etc/thermal-engine.conf \
    vendor/lenovo/x3/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/lenovo/x3/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/lenovo/x3/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so


# Time services - from bardock-pro - OPM1.171019.011
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/lenovo/x3/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so

# Widevine - kanged from Angler OPM3.171019.019
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

# Wifi
PRODUCT_COPY_FILES += \
    vendor/lenovo/x3/proprietary/vendor/bin/cnss-daemon:system/vendor/bin/cnss-daemon

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libloc_ds_api \
    libdiag \
    libdsutils \
    libidl \
    libmm-abl \
    libqcci_legacy \
    libqmi \
    libqmi_cci \
    libqmi_client_qmux \
    libqmiservices \
    libmdmdetect \
    QtiTelephonyService \
    datastatusnotification \
    com.qualcomm.location \
    qcrilmsgtunnel \
    TimeService \
    ims \
    imssettings
